name: 'Build and Deploy to Azure'
env:
    IMAGE_NAME: gthxnetbot
on: 
    push:
        branches: 
           - 'master'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: Initialize submodules
          run: git submodule update --init

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login to Azure docker'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: 'Build and push image'
          run: |
            docker build . --pull -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          run: |
            az container create --name ${{ env.IMAGE_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} -l "west us 2" --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --cpu 1 --memory 1  --environment-variables EmailConfiguration__EmailSubject='Gthx Error' --secure-environment-variables ConnectionStrings__GthxDb='${{ secrets.CONNECTION_STRING }}' EmailConfiguration__FromName='${{ secrets.EMAIL_FROMNAME }}' EmailConfiguration__ToEmail='${{ secrets.EMAIL_TO }}' EmailConfiguration__UserName='${{ secrets.EMAIL_USERNAME }}' EmailConfiguration__Password='${{ secrets.EMAIL_PASSWORD }}' EmailConfiguration__MailServer=${{ secrets.EMAIL_SERVER }} EmailConfiguration__Port=${{ secrets.EMAIL_PORT }} IrcInfo__Channels='${{ secrets.IRC_CHANNELS }}' IrcInfo__Nick=${{ secrets.IRC_NICK }} IrcInfo__Password='${{ secrets.IRC_PASSWORD }}' IrcInfo__RealName='${{ secrets.IRC_REALNAME }}' IrcInfo__Server='${{ secrets.IRC_SERVER}}'
